### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by SamJokO** [gerald-lindsly/mongo-delphi-driver#8]
Hi,

Memory-leak in MongoBson.pas.
TBson.value(name: string): variant;
var
 i : TBsonIterator;
begin
 i := find(name);
 if i = nil then
   Result := Null
 else
 begin
   Result := i.value;
  // Here, i (TBsonIterator) need free.
   i.Free;
 end;
end;

**Comment by gerald-lindsly** [comment]
i updated the repo to reflect your change.  Thanks for your input.
